# Generated by Django 3.2.7 on 2021-09-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoes',
            name='tecnicas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
