# Generated by Django 3.2.7 on 2021-09-16 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('76435ac9-e0db-4cb6-9003-b09dbcb5e41f'), editable=False),
        ),
    ]
