# Generated by Django 3.2.7 on 2021-09-16 01:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_usuario_caminho_armazenamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('ed4c9dd9-ef25-4d87-bb7e-a0c8c8dfa5d8'), editable=False),
        ),
    ]
