# Generated by Django 3.2.7 on 2021-09-16 01:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_usuario_caminho_armazenamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('aad66586-39d6-48a6-8750-0573597a5953'), editable=False),
        ),
    ]
