# Generated by Django 3.2.7 on 2021-09-17 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_auto_20210915_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('fa9197a8-cd96-43a3-87ac-91ae3d3d75f9'), editable=False),
        ),
    ]
