# Generated by Django 3.2.7 on 2021-09-17 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_usuario_caminho_armazenamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('c9a36b3b-1dab-4853-8dd0-86b51b47e092'), editable=False),
        ),
    ]
