# Generated by Django 3.2.7 on 2021-09-17 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_alter_usuario_caminho_armazenamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('cb613dc2-fd8b-4b56-a5f6-b781be1f483e'), editable=False),
        ),
    ]
