# Generated by Django 3.2.7 on 2021-09-28 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_alter_usuario_caminho_armazenamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('f3436952-3a8b-43b7-a738-7c32f582f7ea'), editable=False),
        ),
    ]
