# Generated by Django 3.2.7 on 2021-09-28 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_alter_usuario_caminho_armazenamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('acbd04c4-496b-4729-842c-7c75daffeaa4'), editable=False),
        ),
    ]
