# Generated by Django 3.2.7 on 2021-09-29 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_alter_usuario_caminho_armazenamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('10781210-428f-4186-9358-e447f34a2208'), editable=False),
        ),
    ]
