# Generated by Django 3.2.7 on 2021-09-16 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('texto', models.TextField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('edicao', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('destaque', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('comunicados', 'Comunicados'), ('equipamentos', 'Equipamentos'), ('compras', 'Compras'), ('manutencao', 'Manutenção'), ('treinamentos', 'Treinamentos'), ('pesquisa', 'Pesquisa')], default='comunicados', max_length=15)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
