# Generated by Django 3.2.7 on 2021-09-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_auto_20210917_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='tipo_de_equipamento',
            field=models.CharField(blank=True, choices=[('SEM', 'Microscópio Eletrônico de Varredura'), ('TEM', 'Microscópio Eletrônico de Transmissão'), ('Raman', 'Microscópio Confocal Raman'), ('AFM', 'Microscópio de Força Atômica'), ('Preparo', 'Preparo de Amostra')], max_length=15, null=True),
        ),
    ]
