# Generated by Django 3.2.7 on 2021-09-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_alter_equipamento_tipo_de_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='url_fabricante',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='acessorioequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo_de_equipamento',
            field=models.CharField(choices=[('SEM', 'Microscópio Eletrônico de Varredura'), ('TEM', 'Microscópio Eletrônico de Transmissão'), ('Raman', 'Microscópio Confocal Raman'), ('AFM', 'Microscópio de Força Atômica'), ('Preparo', 'Preparo de Amostra')], max_length=15),
        ),
    ]
