# Generated by Django 3.2.7 on 2021-09-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_equipamento_apelido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorioequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acesorios', to='equipamentos.equipamento'),
        ),
    ]
